describe('Create Contract via Type Form', function()
{
  it('Create Contract', function()
  {
    cy.visit('https://hacktiv8-form.typeform.com/to/UtS16J?product=DBAD')
    cy.get('.ScreenButton__Root-u87sau-0 > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#shortText-name').type('Jamlludin Yahya')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#phone-number-phone').type('084310191919')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#email-email').type('ffadilla@kode.id')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#shortText-identification_number').type('3671091009900001')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.wait(20000)
    cy.get('#shortText-birth_place').type('Jakarta')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#stkv-text-birth_date').type('01021990')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('.auto-size-text-area').type('Jalan Margahayu Blok B1 No 17 Kel.Cibodas Kec. Cibodasari Kota Tangerang')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#shortText-postal_code').type('17161')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#shortText-npwp_number').type('0102199045775')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.wait(10000)
    cy.get('#shortText-bank_account_number').type('7610919112')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#shortText-bank_holder_name').type('Jamlludin Yahya')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('.dropdown__InputWrapper-sc-1w8q90m-3 > .input__InputField-p8yw0p-0').click().get('#choice-5 > .choice__ChoiceTitleWrapper-sc-103qo7w-4 > .choice__ChoiceTitle-sc-103qo7w-0').click()
    cy.get('#shortText-last_education').type('Sarjana Muda')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#shortText-last_academic_institution_name').type('Akademi Pakarthi Luhur')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.wait(10000)
    cy.get('#shortText-family_certificate_number').type('3718181818900011')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.wait(10000)
    cy.get('#shortText-primary_reference_name').type('Ibunya')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#phone-number-primary_reference_phone').type('0873301010404')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#shortText-secondary_reference_name').type('Bapaknya')
    cy.get('.bHvxlx > .submit__Root-sc-1ra8r4w-0 > .submit__SubmitWrapper-sc-1ra8r4w-1 > .hoverable__Root-o9kz04-0 > .button__ButtonWrapper-sc-1g3rldj-0').click()
    cy.get('#phone-number-secondary_reference_phone').type('087701010707')
    cy.get('#phone-number-secondary_reference_phone').type('{enter}')
    cy.get('#block-scroller-secondary_reference_phone > .block-scroller__Positioner-sc-23jz1-1').contains('Submit').click()
    cy.wait(1000)
  })
})